{% set name = "cysignals" %}
{% set version = "1.10.1" %}
{% set sha256 = "dfe63bbe295324bd88e39215db8745a9f81668229e3bd931da1b0757bb45f7b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - upstream_issue88_anonymous.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cython
    - pip
    - pari
  run:
    - python
    - pari

test:
  imports:
    - cysignals

about:
  home: https://github.com/sagemath/cysignals
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'interrupt and signal handling for Cython'

  doc_url: http://cysignals.readthedocs.io
  dev_url: https://github.com/sagemath/cysignals

extra:
  recipe-maintainers:
    - dfroger
    - isuruf
    - saraedum
