{% set name = "cysignals" %}
{% set version = "1.6.8" %}
{% set sha256 = "4d0c7b035edc1d7ac5b4e4264021b5cf06b6f501b328d9892af102caabe50604" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/sagemath/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Decrease-stack-size-in-Makefile.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - setuptools
    - cython
    - pip
    - toolchain
    - pari
  run:
    - python
    - cython
    - pari

test:
  imports:
    - cysignals

about:
  home: https://github.com/sagemath/cysignals
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'interrupt and signal handling for Cython'

  doc_url: http://cysignals.readthedocs.io
  dev_url: https://github.com/sagemath/cysignals

extra:
  recipe-maintainers:
    - dfroger
    - isuruf
    - saraedum
